[package]
name = "nid"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
clap = { version = "4.0", features = ["derive"] }
cli-clipboard = "0.4.0"
